### ISSUE TITLE
Depth is ignored in image recognition

### ISSUE THREAD

**Issue by clange** [lgleim/handsOffMyFace#1]
First of all, this is an excellent initiative!

I noticed that the image recognition currently only works in two dimensions. It does not take into account the "depth" between the user and the camera. Thus, when one places one's hand at a safe distance from the face but in the line between face and camera, the software thinks you are touching your face.

**Comment by lgleim** [comment]
Thanks for the positive feedback!

Unfortunately, monocular depth estimation is a very challenging problem. C.f. this [overview paper](https://arxiv.org/abs/1901.09402) or these [papers with code](https://paperswithcode.com/task/monocular-depth-estimation).

Given the current approach (based on PoseNet), taking depth information into account would require significant additional engineering effort.

I rather consider this project a simple, yet practical tool, which works well if you place your camera at a reasonable angle, intended for short-term usage. Thus, I will not incorporate depth estimation at this time and close this issue, although I see clear merit in the proposition. 

I would love to see more sophisticated solutions, maybe based on depth sensors such as Microsoft Kinect, or sophisticated monocular depth estimation algorithms! Please let me know if you develop or come across such solutions!
